/**
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * The version of the OpenAPI document: 59.6.1
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DestinationInput } from './destinationInput';

/**
 * Input to Add a Destination into an Audience.
 */
export class AddDestinationToAudienceAlphaInput {
    'destination': DestinationInput;
    /**
     * The identifier sync configuration input.
     */
    'idSyncConfiguration'?: object;
    /**
     * The settings that a Destination requires to create audiences on a third-party platform. These settings are Destination-specific and thus are best defined as unknown.
     */
    'connectionSettings'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }> = [
        {
            name: 'destination',
            baseName: 'destination',
            type: 'DestinationInput',
        },
        {
            name: 'idSyncConfiguration',
            baseName: 'idSyncConfiguration',
            type: 'object',
        },
        {
            name: 'connectionSettings',
            baseName: 'connectionSettings',
            type: 'any',
        },
    ];

    static getAttributeTypeMap() {
        return AddDestinationToAudienceAlphaInput.attributeTypeMap;
    }
}
