/**
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * The version of the OpenAPI document: 59.1.0
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * A wrapper object containing compute conditions in a specific format.
 */
export class AudienceConditionsWrapper {
    /**
     * Discriminator field denoting what format the compute conditions are specified in.
     */
    'format': AudienceConditionsWrapper.FormatEnum;
    /**
     * Compute conditions specified in the form denoted by the \'format\' discriminator field.
     */
    'conditions': object | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }> = [
        {
            name: 'format',
            baseName: 'format',
            type: 'AudienceConditionsWrapper.FormatEnum',
        },
        {
            name: 'conditions',
            baseName: 'conditions',
            type: 'object',
        },
    ];

    static getAttributeTypeMap() {
        return AudienceConditionsWrapper.attributeTypeMap;
    }
}

export namespace AudienceConditionsWrapper {
    export enum FormatEnum {
        AST = <any>'AST',
        CQL = <any>'CQL',
    }
}
