/**
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * The version of the OpenAPI document: 62.1.0
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Creates a Transformation Function instance.
 */
export class CreateTransformationFunctionInstanceAlphaInput {
    /**
     * Transformation Function id to which this instance is associated.  Note: Remove the ifnt_ prefix from the id.
     */
    'functionId': string;
    /**
     * The Source or Destination id to be connected.
     */
    'integrationId': string;
    /**
     * The type of Integration this Transformation Function instance is connected to. This field is mandatory for Transformation Function instances.
     */
    'integrationType': string;
    /**
     * Whether this Transformation Function instance should be enabled for the Integration.
     */
    'enabled'?: boolean;
    /**
     * Defines the display name of the Transformation Function instance.
     */
    'name': string;
    /**
     * An object that contains settings for this Transformation Function instance based on the settings present in the Transformation Function class.
     */
    'settings': { [key: string]: any };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }> = [
        {
            name: 'functionId',
            baseName: 'functionId',
            type: 'string',
        },
        {
            name: 'integrationId',
            baseName: 'integrationId',
            type: 'string',
        },
        {
            name: 'integrationType',
            baseName: 'integrationType',
            type: 'string',
        },
        {
            name: 'enabled',
            baseName: 'enabled',
            type: 'boolean',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'settings',
            baseName: 'settings',
            type: '{ [key: string]: any; }',
        },
    ];

    static getAttributeTypeMap() {
        return CreateTransformationFunctionInstanceAlphaInput.attributeTypeMap;
    }
}
