/**
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * The version of the OpenAPI document: 70.0.0
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Search criteria input for list audience consumers.
 */
export class ListAudienceSearchInput {
    /**
     * Field to filter by.
     */
    'type': ListAudienceSearchInput.TypeEnum;
    /**
     * Text to match against the selected field (max 255 characters). When searching by KEY, a prefix match is used. For all other options, a full wildcard search will be used.
     */
    'query': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }> = [
        {
            name: 'type',
            baseName: 'type',
            type: 'ListAudienceSearchInput.TypeEnum',
        },
        {
            name: 'query',
            baseName: 'query',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return ListAudienceSearchInput.attributeTypeMap;
    }
}

export namespace ListAudienceSearchInput {
    export enum TypeEnum {
        DEFINITION = <any>'DEFINITION',
        KEY = <any>'KEY',
        NAME = <any>'NAME',
    }
}
