/**
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * The version of the OpenAPI document: 69.0.0
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IDSyncConfigurationInput } from './iDSyncConfigurationInput';
import { Metadata } from './metadata';

export class SimpleDestination {
    /**
     * The id of the Integration.
     */
    'id': string;
    /**
     * The name of the Destination.
     */
    'name'?: string;
    /**
     * The Source of the Destination.
     */
    'sourceId': string;
    /**
     * Whether the Integration is enabled or not.
     */
    'enabled': boolean;
    /**
     * When the Integration connection was created.
     */
    'createdAt': string;
    /**
     * When the Integration connection was last updated.
     */
    'updatedAt': string;
    /**
     * The Destination settings.
     */
    'settings': { [key: string]: any };
    /**
     * The Destination id.
     */
    'destinationId': string;
    'metadata'?: Metadata;
    /**
     * ID Sync configuration - array of external IDs with their strategies.
     */
    'idSyncConfiguration'?: Array<IDSyncConfigurationInput>;
    /**
     * The settings that a Destination requires to create audiences on a third-party platform. These settings are Destination-specific and thus are best defined as unknown.
     */
    'connectionSettings'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'sourceId',
            baseName: 'sourceId',
            type: 'string',
        },
        {
            name: 'enabled',
            baseName: 'enabled',
            type: 'boolean',
        },
        {
            name: 'createdAt',
            baseName: 'createdAt',
            type: 'string',
        },
        {
            name: 'updatedAt',
            baseName: 'updatedAt',
            type: 'string',
        },
        {
            name: 'settings',
            baseName: 'settings',
            type: '{ [key: string]: any; }',
        },
        {
            name: 'destinationId',
            baseName: 'destinationId',
            type: 'string',
        },
        {
            name: 'metadata',
            baseName: 'metadata',
            type: 'Metadata',
        },
        {
            name: 'idSyncConfiguration',
            baseName: 'idSyncConfiguration',
            type: 'Array<IDSyncConfigurationInput>',
        },
        {
            name: 'connectionSettings',
            baseName: 'connectionSettings',
            type: 'any',
        },
    ];

    static getAttributeTypeMap() {
        return SimpleDestination.attributeTypeMap;
    }
}
