name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: startsWith(github.event.head_commit.message, 'Automated SDK update')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20.17"
          cache: npm

      - name: Install
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --provenance --access public
